### ISSUE TITLE
File Splits larger than 2GB?

### ISSUE THREAD

**Issue by paschott** [MScholtes/SysAdminsFriends#2]
Would it be possible to increase the "int" to a 64-byte int to allow splitting into files larger than 2GB? We have some large files we want to split into something slightly larger than 2GB so they can still transfer, but not create too many files.  I didn't want to break anything so am just trying this at 2GB for now.

**Comment by MScholtes** [comment]
Hello paschott,

I guess you're requesting an advancement for Split-File. It is not as easy as it seems since the .Net method **BinaryReader.Read** I use only supports **Int32** as read length.

Please give me some time to investigate (it's Corona time and I'm at home working and supporting two little children). 

Greetings

Markus

**Comment by paschott** [comment]
I figured it wasn't that easy, but also figured I'd ask. I went with 2GB files and it worked well enough to get me by.  Was just hoping for slightly larger files.  We have some that are too big to transfer over the WAN, but could be broken down to 5-10GB and it would work just fine.

No worries about this as it's not a high priority right now. Just the script was enough to get me by. More segments than I'd want, but it worked.

Thanks.
________________________________

**Comment by MScholtes** [comment]
Hello paschott,

the solution is there with a new Version but it took longer and also did hurt because of the unexpectedly weak implementation of BinaryReader and byte arrays in .Net.
First I made a buffer of 2^32 bytes size, but had to learn that BinaryReader allows only 2^32-1 bytes! So I tried 2^32-1 bytes and had to learn that .Net byte arrays can only have a size of 2^32-57 bytes. Tried this and it broke in a 32 bit Environment that only allows about 1.5 GB of array size.

In between I stumbled over the banker's rounding of PowerShell but I got a working solution with a Buffer size of 1 GB (just to be sure) now.

I hope that's what you can use.

Greetings

Markus

**Comment by MScholtes** [comment]
Closed since no response for 2 weeks
